apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-backend-config
  labels:
    app: auth-backend
data:
  PORT: "3000"
  KEYCLOAK_ISSUER: "http://localhost:8081/realms/internstore"
  KEYCLOAK_JWKS_URI: "http://keycloak:8080/realms/internstore/protocol/openid-connect/certs"
  KEYCLOAK_CLIENT_ID: "internstore-backend"
  INTERNAL_TOKEN_TTL_SECONDS: "60"
  REDIS_URL: "redis://redis:6379"
