apiVersion: v1
kind: Pod
metadata:
  name: peek-node
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["sleep", "3600"]
    volumeMounts:
    - name: kube-etc
      mountPath: /host-kube-etc
      readOnly: true
  volumes:
  - name: kube-etc
    hostPath:
      path: /etc/kubernetes
