apiVersion: v1
kind: Service
metadata:
  name: telemetry-aggregates
  labels:
    app: telemetry-aggregates
spec:
  selector:
    app: telemetry-aggregates
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
