from dataclasses import dataclass


@dataclass
class CheckoutWorkflowItem:
    product_id: str
    quantity: int


# The workflow's sole input — sent as a plain JSON object by Orders'
# POST /checkout/v2 (see orders/routers/checkout_v2.py), which has no
# dependency on this package (separate services, per STR-139's confirmed
# code-placement decision) and so builds this shape by hand rather than
# importing this dataclass. Temporal's default data converter decodes the
# JSON payload into this dataclass on the worker side based on
# CheckoutWorkflow.run's type hint — Orders itself never needs to know
# this type exists, only its field names.
#
# `order_id` is generated by Orders (not by the workflow) before it starts
# the workflow, precisely so create_order (and every other activity below)
# has a stable, idempotency-key-worthy id to key off of from the very first
# attempt — see activities.create_order's docstring.
#
# `amount` is the total to charge, computed server-side by Orders from
# Catalog prices (never trusted from the original HTTP caller) — Payments'
# /charge only simulates outcomes off this amount, it does no pricing of
# its own.
@dataclass
class CheckoutWorkflowInput:
    order_id: str
    owner_id: str
    contact_name: str
    contact_email: str
    contact_phone: str | None
    payment_method: str
    items: list[CheckoutWorkflowItem]
    amount: float


@dataclass
class CheckoutWorkflowResult:
    order_id: str
    status: str  # "confirmed" | "rejected"
