apiVersion: v1
kind: Service
metadata:
  name: postgres-payments
  labels:
    app: postgres-payments
spec:
  selector:
    app: postgres-payments
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
