apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-workflow-worker
  labels:
    app: checkout-workflow-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout-workflow-worker
  template:
    metadata:
      labels:
        app: checkout-workflow-worker
    spec:
      enableServiceLinks: false
      containers:
      - name: checkout-workflow-worker
        image: internstore/checkout-workflow-worker:local
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: checkout-workflow-worker-config
        - secretRef:
            name: checkout-workflow-worker-secret
            optional: true
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
