apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
  annotations:
    # TF: workload_identity_gsa_emails["keycloak"]
    iam.gke.io/gcp-service-account: "internstore-demo-keycloak@PROJECT.iam.gserviceaccount.com"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keycloak-secrets
spec:
  provider: gcp
  parameters:
    # TF: secret_manager_secret_ids[...]
    secrets: |
      - resourceName: "projects/PROJECT/secrets/internstore-demo-keycloak-db-username/versions/latest"
        fileName: "KC_DB_USERNAME"
      - resourceName: "projects/PROJECT/secrets/internstore-demo-keycloak-db-password/versions/latest"
        fileName: "KC_DB_PASSWORD"
      - resourceName: "projects/PROJECT/secrets/internstore-demo-keycloak-admin-password/versions/latest"
        fileName: "KEYCLOAK_ADMIN_PASSWORD"
  secretObjects:
  - secretName: keycloak-secret
    type: Opaque
    data:
    - objectName: "KC_DB_USERNAME"
      key: "KC_DB_USERNAME"
    - objectName: "KC_DB_PASSWORD"
      key: "KC_DB_PASSWORD"
    - objectName: "KEYCLOAK_ADMIN_PASSWORD"
      key: "KEYCLOAK_ADMIN_PASSWORD"
