apiVersion: v1
kind: ServiceAccount
metadata:
  name: temporal
  annotations:
    # TF: workload_identity_gsa_emails["temporal"]
    iam.gke.io/gcp-service-account: "internstore-demo-temporal@PROJECT.iam.gserviceaccount.com"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: temporal-secrets
spec:
  provider: gcp
  parameters:
    # TF: secret_manager_secret_ids["temporal-db-password"]
    secrets: |
      - resourceName: "projects/PROJECT/secrets/internstore-demo-temporal-db-password/versions/latest"
        fileName: "POSTGRES_PWD"
  secretObjects:
  - secretName: temporal-secret
    type: Opaque
    data:
    - objectName: "POSTGRES_PWD"
      key: "POSTGRES_PWD"
