apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-camera
  labels:
    app: mock-camera
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-camera
  template:
    metadata:
      labels:
        app: mock-camera
    spec:
      enableServiceLinks: false
      containers:
      - name: mock-camera
        image: internstore/mock-camera:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        readinessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
