import uuid
from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field

from orders.models import OrderStatus


class CartItemCreate(BaseModel):
    product_id: uuid.UUID
    quantity: int = Field(gt=0)


class CartItemUpdate(BaseModel):
    quantity: int = Field(gt=0)


class CartItemRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    product_id: uuid.UUID
    quantity: int


class CartRead(BaseModel):
    items: list[CartItemRead]


class CheckoutRequest(BaseModel):
    contact_name: str = Field(min_length=1, max_length=255)
    contact_email: str = Field(min_length=1, max_length=255)
    contact_phone: str | None = Field(default=None, max_length=50)
    payment_method: str = Field(min_length=1, max_length=50)


class OrderItemRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    product_id: uuid.UUID
    quantity: int


class OrderRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    status: OrderStatus
    contact_name: str
    contact_email: str
    contact_phone: str | None
    payment_method: str
    created_at: datetime
    items: list[OrderItemRead]


# --- STR-139: Temporal-orchestrated checkout (/checkout/v2), parallel to
# the Kafka-choreographed /checkout above. ---


class CheckoutV2Response(BaseModel):
    workflow_id: str
    # "running" — POST /checkout/v2 hit its wait timeout, caller should poll
    # GET /checkout/v2/{workflow_id}. "confirmed"/"rejected" — the workflow
    # finished within the wait window (or the poll found it finished).
    status: str
    order: OrderRead | None = None


# Body for the create_order activity's call into
# POST /internal/checkout-workflow/orders. `id` is generated by the
# workflow itself (deterministic, via workflow.uuid4()) rather than left to
# Orders to assign — that's what makes the endpoint idempotent by a simple
# primary-key lookup across activity retries, instead of needing a separate
# idempotency-key column.
class WorkflowOrderCreate(BaseModel):
    id: uuid.UUID
    owner_id: str
    contact_name: str
    contact_email: str
    contact_phone: str | None = None
    payment_method: str
    items: list[CartItemCreate]


class WorkflowOrderStatusUpdate(BaseModel):
    status: OrderStatus


class OrderAdminRead(OrderRead):
    # owner_id is a Firebase sub (customer) or auth-backend guest_id (guest
    # checkout) — see Cart.owner_id in orders/models.py. Exposed to admins
    # so they can see who placed the order.
    customer: str


class CheckoutInsufficientStockItem(BaseModel):
    product_id: uuid.UUID
    requested: int
    available: int
    sufficient: bool


class CheckoutInsufficientStockResponse(BaseModel):
    detail: str = "Insufficient stock for one or more items"
    items: list[CheckoutInsufficientStockItem]


class InventoryUnavailableResponse(BaseModel):
    detail: str = "Inventory temporarily unavailable, please retry"
    retry_after_seconds: int = 5


class PaymentIntentRead(BaseModel):
    client_secret: str
