apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: checkout-workflow-worker-secrets
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/example-project-123/secrets/internstore-demo-internal-token-secret/versions/latest"
        fileName: "INTERNAL_TOKEN_SECRET"
  secretObjects:
  - secretName: checkout-workflow-worker-secret
    type: Opaque
    data:
    - objectName: "INTERNAL_TOKEN_SECRET"
      key: "INTERNAL_TOKEN_SECRET"
