apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: orders-secrets
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/example-project-123/secrets/internstore-demo-internal-token-secret/versions/latest"
        fileName: "INTERNAL_TOKEN_SECRET"
      - resourceName: "projects/example-project-123/secrets/internstore-demo-orders-database-url/versions/latest"
        fileName: "DATABASE_URL"
      - resourceName: "projects/example-project-123/secrets/internstore-demo-stripe-secret-key/versions/latest"
        fileName: "STRIPE_SECRET_KEY"
      - resourceName: "projects/example-project-123/secrets/internstore-demo-stripe-webhook-secret/versions/latest"
        fileName: "STRIPE_WEBHOOK_SECRET"
  secretObjects:
  - secretName: orders-secret
    type: Opaque
    data:
    - objectName: "INTERNAL_TOKEN_SECRET"
      key: "INTERNAL_TOKEN_SECRET"
    - objectName: "DATABASE_URL"
      key: "DATABASE_URL"
    - objectName: "STRIPE_SECRET_KEY"
      key: "STRIPE_SECRET_KEY"
    - objectName: "STRIPE_WEBHOOK_SECRET"
      key: "STRIPE_WEBHOOK_SECRET"
