apiVersion: v1
kind: ServiceAccount
metadata:
  name: telemetry-aggregates
  annotations:
    iam.gke.io/gcp-service-account: "internstore-demo-telemetry-aggregates@example-project-123.iam.gserviceaccount.com"
