apiVersion: v1
kind: Service
metadata:
  name: postgres-telemetry-aggregates
  labels:
    app: postgres-telemetry-aggregates
spec:
  selector:
    app: postgres-telemetry-aggregates
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
