apiVersion: v1
kind: Service
metadata:
  name: postgres-catalog
  labels:
    app: postgres-catalog
spec:
  selector:
    app: postgres-catalog
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
