apiVersion: v1
kind: Service
metadata:
  name: postgres-temporal
  labels:
    app: postgres-temporal
spec:
  selector:
    app: postgres-temporal
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
